services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - frontend
      - backend
      - meilisearch
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["sh", "-c", "npm ci --include=dev && npm run dev -- --host 0.0.0.0 --port 5173"]
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started
      frontend-test:
        condition: service_completed_successfully
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - net

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    command: ["sh", "-c", "npm ci --include=dev && npm run test:coverage"]
    restart: "no"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - net

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      backend-test:
        condition: service_completed_successfully
      meilisearch:
        condition: service_started
      postgres:
        condition: service_started
    environment:
      - MEILISEARCH_URL=http://meilisearch:7700
      - DATABASE_URL=postgresql://a3_admin:db_password@postgres:5432/artemis3
    networks:
      - net

  backend-test:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    command: ["sh", "-c", "pytest --cov=app/s3 tests"]
    restart: "no"
    volumes:
      - ./backend:/app
    networks:
      - net

  meilisearch:
    image: getmeili/meilisearch:v1.16
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meilisearch:/meili_data
    environment:
      - MEILI_ENV=development
      - MEILI_HTTP_ADDR=0.0.0.0:7700
    networks:
      - net
      
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=a3_admin
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=artemis3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  meilisearch:
  postgres_data:
